name: "Build Flask app"
description: "Set up environment"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python 3.9
    uses: actions/setup-python@v5
    with:
      python-version: "3.9"
  - name: Install pip and poetry
    shell: bash
    run: |
      python -m pip install --upgrade pip
      python -m pip install poetry==1.8.2
  - name: Configure poetry
    shell: bash
    run: |
      python -m poetry config virtualenvs.in-project true
  - name: Cache the virtualenv
    uses: actions/cache@v4
    with:
      path: ./.venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
  - name: Install dependencies
    shell: bash
    run: |
      python -m poetry install
  - name: Download NLP model
    shell: bash
    run: |
      python -m poetry run python -m spacy download en_core_web_sm
